"""
Filename: gemini.py (Optimized Groq Client Engine)
Description: Drop-in replacement wrapper utilizing the Groq Cloud SDK to execute 
             all-in-one physiological assessments, workouts, and diet generations 
             using strict native JSON mode validation. Enhanced prompt parameters 
             force deeply extended summaries and a minimum of 5 exercises per day.
"""

import os
import json
import logging
from groq import Groq
from dotenv import load_dotenv

# Explicitly load environment variables from your local .env file
load_dotenv()

logging.basicConfig(level=logging.INFO)


class GeminiCoach:
    """Universal coaching wrapper routed through Groq Cloud API endpoints."""

    def __init__(self):
        # Now safely loads the key from system memory after load_dotenv() runs
        api_key = os.environ.get("GROQ_API_KEY")
        
        if not api_key:
            logging.error("[Groq Engine Warning] 'GROQ_API_KEY' environment variable is missing from your .env configuration.")
        
        self.client = Groq(api_key=api_key)
        self.model_name = "llama-3.3-70b-versatile"

    def analyze_all_in_one(self, profile_dict: dict) -> str:
        """
        Transmits complete body metric data vectors to Groq inside a single optimization 
        request token window, enforcing extended breakdowns and a robust 6-day split.
        """
        profile_json = json.dumps(profile_dict, indent=4)

        combined_prompt = f"""
        You are a world-class elite sports scientist, master kinesiology evaluator, and certified sports nutritionist.
        
        Analyze this comprehensive biomechanical and anthropometric data profile generated by computer vision tracking pipelines:
        {profile_json}
        
        You MUST generate a highly comprehensive, rigorous, and completely detailed training and lifestyle program containing three distinct functional sections.

        =========================================
        SECTION 1: ANALYSIS (DEEP PHYSIOLOGICAL EVALUATION)
        =========================================
        - "summary": This MUST be an exhaustive, multi-paragraph, professional diagnostic report. Do not summarize in 2-3 brief lines. You must thoroughly explain the user's specific body architecture type, critically evaluate proportional balances (e.g., shoulder-to-waist ratios, limb lengths), discuss potential hidden muscle compensations, and deeply analyze postural tracking markers (e.g., spinal angles, pelvic tilt, or joint alignment flags).
        - "strengths": List 3 to 5 precise anatomical strength indicators based on their telemetry metrics.
        - "weaknesses": List 3 to 5 clear developmental gaps, structural tracking vulnerabilities, or mobility limitations.
        - "priority_focus": Pinpoint exactly which muscle groups require immediate specialization.
        - "estimated_improvement_time": Provide a realistic adaptation timeline.

        =========================================
        SECTION 2: WORKOUT (INTENSE 6-DAY GYM TIMETABLE)
        =========================================
        - SCHEDULE CONSTRAINT: You must design a 6-Day Training Split. Monday through Saturday MUST be highly active, target-focused workout days. Sunday is the ONLY permissible rest day. 
        - EXERCISE VOLUME CONSTRAINT: For every active workout day (Monday, Tuesday, Wednesday, Thursday, Friday, and Saturday), you MUST prescribe a MINIMUM of 5 to 7 distinct exercises. Each exercise must have clear, targeted compound and isolation roles, set ranges, and specific repetition structures optimized for progressive overload. Empty arrays or minimal 3-exercise routines are strictly forbidden.

        =========================================
        SECTION 3: DIET (SPLIT NUTRITIONAL BLUEPRINT)
        =========================================
        - Provide an exact macro tracking breakdown (Calories, Protein, Carbs, Fats) scaled precisely to their biometric data and training volume.
        - Provide a highly structured single-day meal schedule containing comprehensive, calorie-dense foods split evenly across 'veg' and 'non_veg' options.

        CRITICAL OUTPUT COMPLIANCE RULE:
        You must return ONLY a single valid JSON object that matches the exact field keys and structural schema layout defined below. 
        Do NOT wrap the output inside markdown text block formatting markers (like ```json). 
        Do NOT include any conversational introduction phrases or trailing notes.

        Target Mandatory JSON Schema Layout:
        {{
            "analysis": {{
                "summary": "Exhaustive multi-paragraph professional scientific biomechanical and postural diagnostic breakdown...",
                "strengths": [],
                "weaknesses": [],
                "priority_focus": [],
                "estimated_improvement_time": ""
            }},
            "workout": {{
                "goal": "Selected user baseline training goal",
                "focus_muscles": [],
                "weekly_plan": [
                    {{
                        "day": "Monday",
                        "muscle_group": "Target Muscle Group Splitting",
                        "exercises": [
                            {{"name": "Exercise 1", "sets": 4, "reps": "8-12"}},
                            {{"name": "Exercise 2", "sets": 4, "reps": "10"}},
                            {{"name": "Exercise 3", "sets": 3, "reps": "12"}},
                            {{"name": "Exercise 4", "sets": 3, "reps": "12"}},
                            {{"name": "Exercise 5", "sets": 3, "reps": "15"}},
                            {{"name": "Exercise 6", "sets": 3, "reps": "Failure"}}
                        ]
                    }},
                    {{
                        "day": "Tuesday",
                        "muscle_group": "Target Muscle Group Splitting",
                        "exercises": [
                            {{"name": "Exercise 1", "sets": 4, "reps": "8-12"}},
                            {{"name": "Exercise 2", "sets": 4, "reps": "10"}},
                            {{"name": "Exercise 3", "sets": 3, "reps": "12"}},
                            {{"name": "Exercise 4", "sets": 3, "reps": "12"}},
                            {{"name": "Exercise 5", "sets": 3, "reps": "15"}}
                        ]
                    }},
                    {{
                        "day": "Wednesday",
                        "muscle_group": "Target Muscle Group Splitting",
                        "exercises": [
                            {{"name": "Exercise 1", "sets": 4, "reps": "8-12"}},
                            {{"name": "Exercise 2", "sets": 4, "reps": "10"}},
                            {{"name": "Exercise 3", "sets": 3, "reps": "12"}},
                            {{"name": "Exercise 4", "sets": 3, "reps": "12"}},
                            {{"name": "Exercise 5", "sets": 3, "reps": "15"}}
                        ]
                    }},
                    {{
                        "day": "Thursday",
                        "muscle_group": "Target Muscle Group Splitting",
                        "exercises": [
                            {{"name": "Exercise 1", "sets": 4, "reps": "8-12"}},
                            {{"name": "Exercise 2", "sets": 4, "reps": "10"}},
                            {{"name": "Exercise 3", "sets": 3, "reps": "12"}},
                            {{"name": "Exercise 4", "sets": 3, "reps": "12"}},
                            {{"name": "Exercise 5", "sets": 3, "reps": "15"}}
                        ]
                    }},
                    {{
                        "day": "Friday",
                        "muscle_group": "Target Muscle Group Splitting",
                        "exercises": [
                            {{"name": "Exercise 1", "sets": 4, "reps": "8-12"}},
                            {{"name": "Exercise 2", "sets": 4, "reps": "10"}},
                            {{"name": "Exercise 3", "sets": 3, "reps": "12"}},
                            {{"name": "Exercise 4", "sets": 3, "reps": "12"}},
                            {{"name": "Exercise 5", "sets": 3, "reps": "15"}}
                        ]
                    }},
                    {{
                        "day": "Saturday",
                        "muscle_group": "Target Muscle Group Splitting",
                        "exercises": [
                            {{"name": "Exercise 1", "sets": 4, "reps": "8-12"}},
                            {{"name": "Exercise 2", "sets": 4, "reps": "10"}},
                            {{"name": "Exercise 3", "sets": 3, "reps": "12"}},
                            {{"name": "Exercise 4", "sets": 3, "reps": "12"}},
                            {{"name": "Exercise 5", "sets": 3, "reps": "15"}}
                        ]
                    }},
                    {{
                        "day": "Sunday",
                        "muscle_group": "Rest / Recovery",
                        "exercises": []
                    }}
                ],
                "cardio": "Detailed cardiovascular intensity routine directive...",
                "recovery": "Sleep, hydration, and central nervous system tissue recovery guidelines..."
            }},
            "diet": {{
                "goal": "Nutritional strategy directive statement matching profile constraints...",
                "daily_calories": 2500,
                "protein_g": 160,
                "carbs_g": 270,
                "fat_g": 65,
                "water_liters": 3.5,
                "meal_plan": {{
                    "veg": {{
                        "breakfast": [],
                        "lunch": [],
                        "snack": [],
                        "dinner": []
                    }},
                    "non_veg": {{
                        "breakfast": [],
                        "lunch": [],
                        "snack": [],
                        "dinner": []
                    }}
                }},
                "supplements": [],
                "tips": []
            }}
        }}
        """

        chat_completion = self.client.chat.completions.create(
            model=self.model_name,
            messages=[
                {
                    "role": "user",
                    "content": combined_prompt,
                }
            ],
            response_format={"type": "json_object"},
            temperature=0.4
        )
        
        return chat_completion.choices[0].message.content