"""
Filename: body_profile.py
Description: Master dataclass objects storing type-safe sub-profiles, measurements, 
             and evaluation states across the processing lifecycle pipelines.
"""

from dataclasses import dataclass, field, asdict
from typing import Dict, Any


@dataclass
class UserProfile:
    """Stores user personal information."""
    name: str = ""
    age: int = 0
    gender: str = ""
    height_cm: float = 0.0
    weight_kg: float = 0.0
    goal: str = ""


@dataclass
class ViewAnalysis:
    """Stores analysis for one body view."""
    view: str = ""
    analysis_quality: Dict[str, Any] = field(default_factory=dict)
    measurements: Dict[str, Any] = field(default_factory=dict)
    derived_ratios: Dict[str, Any] = field(default_factory=dict)
    bilateral_symmetry: Dict[str, Any] = field(default_factory=dict)
    validation_warnings: list = field(default_factory=list)


@dataclass
class BodyScoreProfile:
    """
    Stores finalized assessment score parameters. 
    Renamed to prevent namespace naming conflicts with the computational evaluation engines.
    """
    overall: float = 0.0
    shoulders: float = 0.0
    chest: float = 0.0
    waist: float = 0.0
    hips: float = 0.0
    posture: float = 0.0
    symmetry: float = 0.0
    body_type: str = ""


@dataclass
class AIAnalysis:
    """Gemini output assessment text structures."""
    summary: str = ""
    strengths: list = field(default_factory=list)
    weaknesses: list = field(default_factory=list)
    recommendations: list = field(default_factory=list)
    workout_focus: list = field(default_factory=list)
    diet_tips: list = field(default_factory=list)


@dataclass
class WorkoutPlan:
    """Workout generated by Gemini."""
    weekly_plan: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DietPlan:
    """Diet generated by Gemini."""
    calories: int = 0
    protein: int = 0
    carbs: int = 0
    fats: int = 0
    meals: Dict[str, Any] = field(default_factory=dict)


@dataclass
class BodyProfile:
    """Master object used throughout the data evaluation lifecycle pipelines."""

    user: UserProfile = field(default_factory=UserProfile)
    front: ViewAnalysis = field(default_factory=ViewAnalysis)
    side: ViewAnalysis = field(default_factory=ViewAnalysis)
    back: ViewAnalysis = field(default_factory=ViewAnalysis)
    score: BodyScoreProfile = field(default_factory=BodyScoreProfile) # <-- Aligned to new unique dataclass wrapper
    ai: AIAnalysis = field(default_factory=AIAnalysis)
    workout: WorkoutPlan = field(default_factory=WorkoutPlan)
    diet: DietPlan = field(default_factory=DietPlan)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self):
        """Convert complete profile tree into a native dictionary."""
        return asdict(self)

    def update_user(self, name, age, gender, height, weight, goal):
        self.user = UserProfile(
            name=name,
            age=age,
            gender=gender,
            height_cm=height,
            weight_kg=weight,
            goal=goal
        )

    def update_front(self, front_data):
        self.front = ViewAnalysis(**front_data)

    def update_side(self, side_data):
        self.side = ViewAnalysis(**side_data)

    def update_back(self, back_data):
        self.back = ViewAnalysis(**back_data)

    def update_score(self, score_data):
        """
        Safely translates calculations from the scoring engine into 
        the data container fields, filtering out unmapped peripheral parameters.
        """
        # If score_data is nested under another scores key from the dictionary export, unpack it
        if "scores" in score_data and isinstance(score_data["scores"], dict):
            raw_scores = score_data["scores"]
        else:
            raw_scores = score_data

        # Map explicitly known fields safely without breaking on structural back/arms indices
        self.score = BodyScoreProfile(
            overall=float(score_data.get("overall_score", raw_scores.get("overall", 0.0))),
            shoulders=float(raw_scores.get("shoulders", 0.0)),
            chest=float(raw_scores.get("chest", 0.0)),
            waist=float(raw_scores.get("waist", 0.0)),
            hips=float(raw_scores.get("hips", 0.0)),
            posture=float(raw_scores.get("posture", 0.0)),
            symmetry=float(raw_scores.get("symmetry", 0.0)),
            body_type=str(score_data.get("body_type", "Balanced"))
        )

    def update_ai(self, ai_data):
        self.ai = AIAnalysis(**ai_data)

    def update_workout(self, workout_data):
        self.workout = WorkoutPlan(weekly_plan=workout_data)

    def update_diet(self, diet_data):
        self.diet = DietPlan(**diet_data)