import json


class BodyAnalysisTemplate:
    """
    Prompt template for complete body analysis.

    This template receives ONLY structured data generated by
    the computer vision pipeline.

    Gemini NEVER analyzes images directly.
    """

    @staticmethod
    def build(profile: dict):

        payload = {

            "user": profile.get("user", {}),

            "front": profile.get("front", {}),

            "side": profile.get("side", {}),

            "back": profile.get("back", {}),

            "score": profile.get("score", {})

        }

        profile_json = json.dumps(
            payload,
            indent=4
        )

        return f"""
You are an elite AI Fitness Coach.

You are NOT analyzing an image.

The measurements below were generated by a computer vision system.

Analyze ONLY the provided data.

Never invent measurements.

Never guess values.

If some information is missing, simply ignore it.

Be objective and professional.

--------------------------------------------------

BODY PROFILE

{profile_json}

--------------------------------------------------

Tasks

1.
Determine the overall body condition.

2.
Identify strong muscle groups.

3.
Identify weak muscle groups.

4.
Identify posture issues.

5.
Identify symmetry problems.

6.
Estimate body type.

7.
Explain whether the body is balanced.

8.
Recommend which muscles should receive the highest priority.

9.
Provide practical improvement advice.

10.
Estimate the expected improvement timeline.

--------------------------------------------------

Return ONLY valid JSON.

Schema:

{{
    "summary": "",

    "body_type": "",

    "overall_condition": "",

    "strengths": [],

    "weaknesses": [],

    "posture": [],

    "symmetry": [],

    "priority_focus": [],

    "recommendations": [],

    "estimated_improvement_time": "",

    "motivation": ""
}}

Do NOT use Markdown.

Do NOT explain your reasoning.

Return ONLY JSON.
"""