import json


class WorkoutPromptTemplate:
    """
    Prompt template for generating a personalized workout plan.
    """

    @staticmethod
    def build(profile: dict):

        payload = {

            "user": profile.get("user", {}),

            "score": profile.get("score", {}),

            "front": profile.get("front", {}),

            "side": profile.get("side", {}),

            "back": profile.get("back", {})

        }

        profile_json = json.dumps(
            payload,
            indent=4
        )

        return f"""
You are an expert fitness coach.

Below is a body analysis generated by a computer vision system.

{profile_json}

Your task:

1. Analyze weak muscle groups.

2. Prioritize muscle development.

3. Generate a 7-day workout plan.

4. Use progressive overload principles.

5. Recommend compound and isolation exercises.

6. Include warm-up and stretching.

Return ONLY valid JSON.

JSON Schema:

{{
    "goal": "",

    "focus_muscles": [],

    "weekly_plan": [

        {{
            "day": "Monday",

            "muscle_group": "",

            "exercises": [

                {{
                    "name": "",

                    "sets": 4,

                    "reps": "8-12"
                }}
            ]
        }}

    ],

    "cardio": "",

    "recovery": ""
}}

Return ONLY JSON.
"""